spring.application.name=Json-Storage-Project



# Database
spring.datasource.url= jdbc:mysql://localhost:3306/data_set_json_record
spring.datasource.username=root
spring.datasource.password=7004765580@Mk